import os
import json
import csv
import io
from typing import List, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.models.models import Campaign, MetaAdSet, MetaAd, Creative, Insight

REPORTS_DIR = "/tmp/metamind_reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

async def fetch_report_data(report_type: str, date_range: str, filters: dict, db: AsyncSession) -> List[Dict[str, Any]]:
    """Fetch analytics data strictly from local PostgreSQL database."""
    if report_type in ["Campaign Performance", "Executive Summary", "ROAS Report", "CPA Report", "CTR Report", "Budget Utilization", "Conversion Report", "Daily Report", "Weekly Report", "Monthly Report", "Custom Date Range"]:
        stmt = select(Campaign)
        res = await db.execute(stmt)
        campaigns = res.scalars().all()
        data = []
        for c in campaigns:
            data.append({
                "ID": c.campaign_id,
                "Name": c.name,
                "Status": c.status,
                "Objective": c.objective or "OUTCOME_SALES",
                "Daily Budget ($)": c.daily_budget or 0.0,
                "Spend ($)": c.spend or 0.0,
                "Revenue ($)": c.revenue or 0.0,
                "ROAS": c.roas or 0.0,
                "CTR (%)": c.ctr or 0.0,
                "Purchases": c.purchases or 0
            })
        return data

    elif report_type == "Ad Set Performance":
        stmt = select(MetaAdSet)
        res = await db.execute(stmt)
        adsets = res.scalars().all()
        return [{
            "AdSet ID": a.adset_id,
            "Name": a.name,
            "Campaign ID": a.campaign_id,
            "Status": a.status,
            "Daily Budget ($)": a.daily_budget or 0.0,
            "Optimization Goal": a.optimization_goal or "CONVERSIONS",
            "Spend ($)": a.spend or 0.0,
            "CPA ($)": a.cpa or 0.0
        } for a in adsets]

    elif report_type == "Ads Performance":
        stmt = select(MetaAd)
        res = await db.execute(stmt)
        ads = res.scalars().all()
        return [{
            "Ad ID": a.ad_id,
            "Name": a.name,
            "AdSet ID": a.adset_id,
            "Status": a.status,
            "Format": a.format or "SINGLE_IMAGE",
            "Spend ($)": a.spend or 0.0,
            "CTR (%)": a.ctr or 0.0,
            "CPC ($)": a.cpc or 0.0
        } for a in ads]

    elif report_type == "Creative Performance":
        stmt = select(Creative)
        res = await db.execute(stmt)
        creatives = res.scalars().all()
        return [{
            "Creative ID": c.creative_id,
            "Name": c.name,
            "Format": c.format_type or "image",
            "Hook Rate (%)": c.hook_rate or 0.0,
            "Hold Rate (%)": c.hold_rate or 0.0,
            "Fatigue": c.fatigue_level or "Low"
        } for c in creatives]

    else:
        stmt = select(Campaign)
        res = await db.execute(stmt)
        campaigns = res.scalars().all()
        return [{
            "ID": c.campaign_id,
            "Name": c.name,
            "Status": c.status,
            "Spend ($)": c.spend or 0.0,
            "Revenue ($)": c.revenue or 0.0,
            "ROAS": c.roas or 0.0
        } for c in campaigns]

def generate_csv_report(filename: str, report_title: str, data: List[Dict[str, Any]]) -> str:
    file_path = os.path.join(REPORTS_DIR, f"{filename}.csv")
    if not data:
        data = [{"Status": "No data available in local PostgreSQL database"}]

    headers = list(data[0].keys())
    with open(file_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(data)
    return file_path

def generate_excel_report(filename: str, report_title: str, data: List[Dict[str, Any]]) -> str:
    # Generates clean TSV/Spreadsheet formatted Excel document (.xlsx / .csv compatible)
    file_path = os.path.join(REPORTS_DIR, f"{filename}.xlsx")
    if not data:
        data = [{"Status": "No data available"}]

    headers = list(data[0].keys())
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(f"Report Title:\t{report_title}\n")
        f.write("Generated By:\tMetaMind AI Enterprise Engine\n\n")
        f.write("\t".join(headers) + "\n")
        for row in data:
            f.write("\t".join(str(row.get(h, "")) for h in headers) + "\n")
    return file_path

def generate_pdf_report(filename: str, report_title: str, data: List[Dict[str, Any]]) -> str:
    # Generates professional formatted branded PDF/HTML document
    file_path = os.path.join(REPORTS_DIR, f"{filename}.pdf")
    if not data:
        data = [{"Status": "No data available"}]

    headers = list(data[0].keys())
    
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{report_title}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; padding: 40px; background: #fafafa; }}
        .header {{ border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }}
        .title {{ font-size: 24px; font-weight: bold; color: #0f172a; }}
        .subtitle {{ font-size: 12px; color: #64748b; margin-top: 5px; }}
        .brand {{ font-size: 18px; font-weight: 800; color: #2563eb; letter-spacing: -0.5px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        th {{ background: #f1f5f9; color: #334155; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; padding: 12px 16px; text-align: left; border-bottom: 1px solid #e2e8f0; }}
        td {{ padding: 12px 16px; font-size: 12px; border-bottom: 1px solid #f1f5f9; color: #334155; }}
        tr:hover {{ background: #f8fafc; }}
        .footer {{ margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 11px; color: #94a3b8; display: flex; justify-content: space-between; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="brand">METAMIND AI ENTERPRISE</div>
            <div class="title">{report_title}</div>
            <div class="subtitle">Source: Local PostgreSQL Database | Generated automatically</div>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                {"".join(f"<th>{h}</th>" for h in headers)}
            </tr>
        </thead>
        <tbody>
            {"".join("<tr>" + "".join(f"<td>{row.get(h, '')}</td>" for h in headers) + "</tr>" for row in data)}
        </tbody>
    </table>

    <div class="footer">
        <div>MetaMind AI Enterprise Reporting Engine</div>
        <div>Confidential & Proprietary</div>
    </div>
</body>
</html>
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    return file_path
